### ISSUE TITLE
Hyperlink formatting

### ISSUE THREAD

**Issue by sbihorel** [mlampros/My.CVitae#1]
Hi,

The example section of the vitae package directed me to your github repo. I really liked the layout of your CV and am  glad that you shared it with the community. I took the liberty to clone your repo and use it as a starting point for my own CV. Now, I am trying to modify some elements of formatting and find myself unable to change the color of hyperlinks (using the \hypersetup block of the .cls file). With the default awesomeCV template, modifying the hypersetup impacts the formatting in the pdf... but using your cls file, some settings have an influence while others like the font color don't (eg, filecolor, urlcolor, linkcolor,...).  My LaTeX skills are too limited to identify why this is the case and was wondering if you would mind shedding some light on the matter.

Thanks in advance

Sebastien

**Comment by mlampros** [comment]
hi @sbihorel and I'm glad you find my version of awesomeCV useful.

I'll tell you the truth, I also struggled a bit to make it work especially when trying to change the colors of the titles, but I definitely didn't touch the [awesome-cv.cls](https://github.com/mlampros/My.CVitae/blob/master/docs/awesome-cv.cls) file because I also have rudimentary LaTeX skills. From what I see there aren't many [issues related to hyperlink colors](https://github.com/posquit0/Awesome-CV/issues?q=hyperlink+color). If you make it work let me know because I'll be interested too to modify the color of the e-mail, blog etc. at the top of the CV

**Comment by sbihorel** [comment]
Hi
Thank you for your response. After I sent my original post, I stumbled upon [issue 175](https://github.com/mitchelloharawild/vitae/issues/175) on vitae github which suggested a path forward. To generalize the suggested solution, my current workaround involves modifying the .cls file to create 2 new latex commands (\darkhref and \lighthref) which I then use in the Rmd instead of \href call.

I highlighted the important bits of change in the cls file below. Note that I created 2 distinct commands to show links displayed in small font with a darker font, than those displayed in a bigger font or bold.

```
\RequirePackage[unicode]{hyperref} 
\hypersetup{%
  pdftitle={},
  pdfauthor={},
  pdfsubject={},
  pdfkeywords={}
  colorlinks=true,
  pdfborder=0
}
...
% Hyperlink colors
\definecolor{darklink}{HTML}{005F9A}
\definecolor{lightlink}{HTML}{009ACD}
...
\newcommand{\darkhref}[2]{\href{#1}{\textcolor{darklink}{#2}}}
\newcommand{\lighthref}[2]{\href{#1}{\textcolor{lightlink}{#2}}}
```

**Comment by mlampros** [comment]
thank you for the code snippet, you are more advanced than I am in LaTeX. I can add these lines of code in the 'awesome-cv.cls' file (darkhref, lighthref), but is a user allowed then to modify the header of the .Rmd file using an ```\href``` in places such as in the [www](https://github.com/mlampros/My.CVitae/blob/master/docs/cv.Rmd#L7) and [email](https://github.com/mlampros/My.CVitae/blob/master/docs/cv.Rmd#L8) or is only meant for the body of the .Rmd file?

**Comment by sbihorel** [comment]
The \darkhref and \lighthref are just wrapper commands around the native \href. the \href command is still available and behaves as it does right now.

**Comment by mlampros** [comment]
yes you are right. I added the [latex code snippets in the 'awesome-cv.cls' file](https://github.com/mlampros/My.CVitae/commit/cdf1c46d2700a0fe2dec96b49e3d1fa98433c020) and replaced the '\href' with '\lighthref' and it works for the hyperlinks. One think that was added too is the [box around the hyperlinks in cyan color](https://raw.githubusercontent.com/mlampros/My.CVitae/master/docs/cv.pdf). I'm ok with this too, but do you know why it happens? It appears only in the .html version and not in the [.pdf file](https://github.com/mlampros/My.CVitae/blob/master/docs/cv.pdf)

**Comment by sbihorel** [comment]
Adding `pdfborder=0` in the \hypersetup call controls the creation of border around links in the pdf, but I don't know about what control this for the html output. I don't create an html output in my setup... how do you do that?

**Comment by mlampros** [comment]
the .html version is actually the cv.pdf file by making a url using ```https://raw.githubusercontent.com/``` (I also mention it in the README.md). Your LaTeX modifications are ok (even with the border included in the .html version). thanks again for making me aware of these changes.
